# Generated by Django 4.2.20 on 2025-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('NEWS', 'Новость')], max_length=7),
        ),
    ]
