# Generated by Django 4.2.20 on 2025-04-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ARTICLE', 'Статья'), ('NEWS', 'Новость')], default='NEWS', max_length=7),
        ),
    ]
