# Generated by Django 4.2.20 on 2025-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('NEWS', 'Новость'), ('ARTICLE', 'Статья')], default='NEWS', max_length=7),
        ),
    ]
