# Generated by Django 4.2.20 on 2025-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_alter_post_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('news', 'Новость'), ('article', 'Статья')], default='news', max_length=7),
        ),
    ]
